### ISSUE TITLE
"LibPetJournal-2.0" error on login

### ISSUE THREAD

**Issue by SiderealDay** [b-morgan/Skillet#15]
<Please include the Skillet version number (from the title or the .toc file)>
<Please include the output of "/dump GetLocale()" if it is different than enUS>

Skillet 4.27 Alpha

Getting this error on login, not 100% sure if from skillet or something else?

```
5x ...ks\Libraries\LibPetJournal-2.0\LibPetJournal-2.0-33.lua:103: ClearFilters() already called
[string "=[C]"]: ?
[string "@ElvUI_ChatTweaks\Libraries\LibPetJournal-2.0\LibPetJournal-2.0-33.lua"]:103: in function `ClearFilters'
[string "@ElvUI_ChatTweaks\Modules\Companions-Companions.lua"]:44: in function `SendZoneList'
[string "@ElvUI_ChatTweaks\Modules\Companions-Companions.lua"]:79: in function `?'
[string "@Skillet\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...let\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Skillet\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...let\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Skillet\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Skillet\Libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...ceSkillet\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>
```

**Comment by b-morgan** [comment]
This is an unfortunate side effect of how ACE3 libraries work. Each addon that uses ACE3 libraries attempts to load their version of each library. During this process, the version number of the local copy is compared with the version number of the copy already loaded in memory and the highest version gets loaded. All addons that use that library will use the single copy in memory.

When an ACE3 library error occurs, the addon from which the in memory copy was loaded often gets (falsely) blamed. This is usually the addon most recently updated so naturally, the error must be caused by that most recent update.

Skillet is not causing this error. Skillet does not use LibPetJournal-2.0. It does use CallbackHandler-1.0 so its copy must be the most up to date.

**Comment by SiderealDay** [comment]
Ty kindly! Do you know from the log above if the error caused by ElvUI_ChatTweaks?
Also, would you know of any workarounds, like can I replace their LibPet with a newer version?

**Comment by b-morgan** [comment]
Your guess is as good as mine. ChatTweaks is certainly a candidate. [LibPetJournal-2.0](https://www.curseforge.com/wow/addons/libpetjournal-2-0) doesn't appear to have been updated since 2018.

You have a better chance of getting help from the [ElvUI](https://www.tukui.org/download.php?ui=elvui) folks.

**Comment by SiderealDay** [comment]
Ty anyway for your help and Skillet! :)
