### ISSUE TITLE
[Feature Request] Compact craftable quantities

### ISSUE THREAD

**Issue by MorbidMind** [b-morgan/Skillet#19]
Hi,

I think it would be good if the right column with craftable quantities had an option of a compact view (or even by default), hiding the zero values.

Right now it shows three numbers, with yellow and orange being zeros for most of the time.

**Comment by b-morgan** [comment]
At the top of the column over the numbers is a "bag" icon. Right-Click on that icon and you can turn off or on each set of numbers. You can customize each profession separately. With the exception of owned, if all of the selected columns are zero, the display is suppressed. If any of the columns is non-zero, all of the selected columns are displayed.

This format was chosen (as opposed to fixed width vertical columns) because there's not a lot of room on the line to display all of the information Skillet-Classic can display.

If you have a specific alternate format in mind, please detail it here.

**Comment by MorbidMind** [comment]
Sorry for missing it, I didn't see it in the appearance settings, so I thought there is no possibility to hide it.

Would it be possible to change it from all-or-nothing to just showing the non-zero values?

**Comment by b-morgan** [comment]
The decision to display or not is in `...\Skillet-Classsic\UI\MainFrame.lua` lines 1132-1177. The actual format of the output is 1162-1174. You can change it to how you would like it to appear. When you have something you like, post it here and we can discuss options.
