### ISSUE TITLE
Can't Craft Rank 3 Umbrahide

### ISSUE THREAD

**Issue by Galthariel** [b-morgan/Skillet#27]
Version I'm using is 
Skillet-4.35

An image says more than 1000 words :-)

![2021-09-21_9-22-28](https://user-images.githubusercontent.com/51491805/134172604-95c47706-2ba1-4656-ac60-2461d99df3d6.png)

**Comment by b-morgan** [comment]
You have reported two issues here. Please report the second, intermittent, problem as a separate issue.

For the main issue, we need to turn on debugging so I can examine the output. Please type "/skillet debuglevel 3", "/skillet tabledump on", and then "/skillet debugshow on". You can check the status with "/skillet debugstatus".

Get the error message again, logoff, and then zip up the per character saved variables file and attach it here.

Turn off logging to chat with "/skillet debugshow off". This will leave logging to character specific saved variables file but the overhead is minimal.

Since this error is caused when testing the return of a Blizzard API function, I took a look at Blizzard's code and determined that there may be a missing parameter to that call. After gathering the debug information from the existing code, please change line 366 in SkilletQueue.lua from:
```
			local recipeInfo = C_TradeSkillUI.GetRecipeInfo(command.recipeID)
```
to:
```
			local recipeInfo = C_TradeSkillUI.GetRecipeInfo(command.recipeID, command.recipeLevel)
```
and see if that fixes the problem. If not, send another zip file.

**Comment by Galthariel** [comment]
Here is the file you've asked and yes, changing line 366 fixed the issue :-)

[Skillet.lua_Galthariel.zip](https://github.com/b-morgan/Skillet/files/7206590/Skillet.lua_Galthariel.zip)

I also removed the other issue from this thread and created a new one :-)

thanks,

**Comment by b-morgan** [comment]
I'll make the change to line 366 and release a new version. Thanks for your help!

**Comment by Galthariel** [comment]
Anytime
