### ISSUE TITLE
Skillet window is not showing up

### ISSUE THREAD

**Issue by ishirra** [b-morgan/Skillet#3]
When trying to open a profession window, the skillet window is not opening up.  Nothing is happening, and I have to disable Skillet to be able to see my profession window.

I received below LUA-error:

14x Skillet\SkilletQueue.lua:660: attempt to compare number with nil
[string "@Skillet\SkilletQueue.lua"]:660: in function `ScanQueuedReagents'
[string "@Skillet\SkilletData.lua"]:1313: in function <Skillet\SkilletData.lua:924>
[string "@Skillet\SkilletData.lua"]:1347: in function `RescanTrade'
[string "@Skillet\Skillet-4.22.lua"]:1023: in function `SkilletShowWindow'
[string "@Skillet\Skillet-4.22.lua"]:848: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by b-morgan** [comment]
What version of Skillet (from the .toc file since the window doesn't open)?

I'm going to guess that you had items in the Skillet queue when you updated Skillet to the version you are now using. The simplest fix would be to delete (or rename) the global saved variables file Skillet.lua. If, however, you wish to retain your queues (on this or other characters), then you can edit SkilletQueue.lua line 660 to be:

`				if command.recipeLevel and command.recipeLevel > 0 then
`

**Comment by ishirra** [comment]
Version is 4.22.  It's not the .old version but the newly created.
I have now deleted the Saved Variables, all which I could find for Skillet, and restarted the game.

The window now pops up, so I am guessing there was still something in my queue.
Thank you for your help!
