### ISSUE TITLE
[Suggestion for Improvement] Era Filter

### ISSUE THREAD

**Issue by Earthling-Z3R0** [b-morgan/Skillet#48]
Hey there, great addon -- been using it for years and each time I play :)

I know you can collapse old era recipe trees (i.e. TBC, BfA, etc) in the skillet window but when I switch to a different tradeskill view, it turns back to including all eras when returning to the tradeskill view I switched from.

**I would like to see an option to filter out anything that is not current era as the default view
 or alternatively
remember my setting to only view the category I selected (e.g. SL recipes) between sessions.**

Thank you for this great addon! The feature I like the most is automatically queueing prerequired items when crafting a "complex" item. Very useful for any tradeskill but imo even more so for engineering :)

**Comment by b-morgan** [comment]
I believe the solution to this issue is to use the custom groups feature of Skillet. You can create one or more custom groups and populate them with the recipes you are most interested in.

Skillet is supposed to remember the custom groups between sessions but I just did a quick test and that appears to be broken. I'll get that fixed in a bit. 

It's pretty easy to recreate a group if you want all of shadowlands then click on the first recipe, scroll to the last recipe and shift-click to select the whole group, then right-click and select copy. Switch to your custom group, right-click and select paste.

**Comment by b-morgan** [comment]
The two biggest problems with remembering the state of categories are 1) A new data structure is needed to remember the state and 2) Skillet has to expand all the categories in order to scan all the recipes.

If custom groups didn't exist, I would probably bite the bullet and implement the above but it has only been asked for a couple of times so I don't believe its worth the effort.
