### ISSUE TITLE
Error with Auctionator

### ISSUE THREAD

**Issue by Galthariel** [b-morgan/Skillet#5]
Version 4.22

203x Skillet\Plugins\Auctionator-518 (alpha).lua:309: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Skillet\Plugins\Auctionator-518 (alpha).lua"]:309: in function `GetExtraText'
[string "@Skillet\SkilletPlugin.lua"]:149: in function `GetExtraText'
[string "@Skillet\UI\MainFrame.lua"]:1991: in function `UpdateDetailsWindow'
[string "@Skillet\UI\MainFrame.lua"]:919: in function <Skillet\UI\MainFrame.lua:894>
[string "=[C]"]: in function `UpdateTradeSkillWindow'
[string "@Skillet\Skillet-4.22.lua"]:870: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by b-morgan** [comment]
I cannot reproduce this error with either Auctionator-518-alpha or Auctionator-9.0.6.1. Since 518-alpha is not the latest version, I'd suggest installing the latest alpha and trying again.

If it still fails, I will need (at a minimum) the steps used to cause the error. Screenshots of the recipe used or the shopping list used, and a copy of your global saved variables file Skillet.lua

**Comment by b-morgan** [comment]
The next release will check for a bad argument.

**Comment by Galthariel** [comment]
No more errors with the latest releases of Auctionator and Skillet
