### ISSUE TITLE
Missing improvement pattern descriptions

### ISSUE THREAD

**Issue by Met7** [b-morgan/Skillet#50]
In the original gui, some eng patterns - the item improvements - do not have description on the item/icon itself, but in a text under it. Skillet does not use those texts and so those patterns have no description at all. E.g. Nitro Boosts.

v 1.50 (30400)

**Comment by b-morgan** [comment]
This issue should be posted against [Skillet-Classic](https://github.com/b-morgan/Skillet-Classic/issues). I have created issue [#120](https://github.com/b-morgan/Skillet-Classic/issues/120) and I believe it has been fixed in 1.51. Please update to the latest version of Skillet-Classic and the let me know (in the Skillet-Classic issue) if it is fixed or not.
