### ISSUE TITLE
Changing professions possible solution

### ISSUE THREAD

**Issue by Tarkumi** [b-morgan/Skillet#62]
You should try to use 
CastSpell(offset+1,BOOKTYPE_PROFESSION) to change professions with the buttons on the top right.
You can get the offset with the GetProfessionInfo function like you do in SkilletData.lua.

**Comment by b-morgan** [comment]
Is there a problem this is a solution for?

**Comment by Tarkumi** [comment]
Yes, sorry.

When I try to change professions (I have Engineering and Enchanting as primary), switching to Enchanting and to Cooking with the buttons works, but when I click on Engineering I get the following error:

![SkilletError](https://user-images.githubusercontent.com/455295/203818765-6ced29a9-aea3-4036-a63e-b62305fb595f.jpg)

**Comment by b-morgan** [comment]
I believe this is a Blizzard bug. It occasionally fails but I have a workaround that works for me. If I open all my professions with an action button at the beginning of a session, then after that the Skillet trade buttons seem to work flawlessly.

**Comment by b-morgan** [comment]
The zip file below contains versions of `Skillet.lua` and `SkilletData.lua` which change the `CastSpellByName` to your suggested `CastSpell(offset+1,BOOKTYPE_PROFESSION)`. Since the original version doesn't fail for me all the time, I'll need some additional testing from you. Let me know, please.

[Skillet.zip](https://github.com/b-morgan/Skillet/files/10086774/Skillet.zip)

**Comment by Tarkumi** [comment]
Thank you, it's working perfectly.

**Comment by b-morgan** [comment]
[Skillet-5.00-alpha18](https://www.curseforge.com/wow/addons/skillet/files/4123569) contains this fix.
