### ISSUE TITLE
Favorites filter showing all group sections with Blizzard grouping

### ISSUE THREAD

**Issue by DonSerrot** [b-morgan/Skillet#7]
This is another issue that seems to only effect versions newer than 4.20. With grouping set to Blizzard and showing only favorite recipes I still get all the other groups without favorites in them visible. As an experiment I tried replacing the RecipieGroups.lua file from 4.24 with the one from 4.20 and so far I haven't seen any errors and the groups once again only show the ones with favorites in them.

**Comment by b-morgan** [comment]
There are a lot of comment changes and commented out debug statements but only two lines of actual code that are commented when perhaps they shouldn't be. If you are comfortable with editing instead of replacing, in the 4.24 version of RecipeGroups.lua, remove the "--" from the beginning of lines 405 and 406. They should look like:
```
		table.remove(list, num + index)
		num = num - 1
```
The difference between 4.20 and 4.24 should now be that empty groups with a progress bar should remain visible. Let me know if that annoys you and I'll see what I can do about it. 

There is a "bug" in Skillet that currently only shows up with Mining where the Shadowlands Mining and the Draenor Mining group headers (with progress bars) don't show because they have no recipes assigned to them. I had a fix that worked for Mining but it screwed up every other profession so I backed it out (except for the two lines above :smile:)

**Comment by DonSerrot** [comment]
It's not ideal, but it's certainly better than having all of the empty groups visible. Hopefully a better solution to the problem will present itself, but for now this works so no rush.

**Comment by b-morgan** [comment]
Skillet-4.25-alpha should fix this issue along with adding an option for empty groups with progress bars.
