### ISSUE TITLE
Quality mats not added to shopping list

### ISSUE THREAD

**Issue by bobolosier** [b-morgan/Skillet#77]
<Please include the Skillet version number (from the title or the .toc file)>
version 5.03 alpha7
<Please include the output of "/dump GetLocale()" if it is different than enUS>
frFR

Materials with several quality levels are not added to shopping list.

**Comment by b-morgan** [comment]
[Skillet-5.03-alpha8](https://www.curseforge.com/wow/addons/skillet/files/4312516) will add the base quality of modified reagents (those with several quality levels) to the shopping list.

Skillet's internal databases were never designed for items with multiple qualities so I'm guessing this is just the tip of the iceberg. I need to know what you want you want to do next (i.e. what are you going to do with the shopping list).

Having just the base quality level in the Shopping List should work for interacting with the AH, it should work with merchants (because they don't sell them), but it probably isn't going to work to fetch reagents from the bank(s).

**Comment by bobolosier** [comment]
Thank you. It is to buy to AH.

**Comment by bobolosier** [comment]
It works. Thank you.
