### ISSUE TITLE
Fail to create certain jewelcrafting items

### ISSUE THREAD

**Issue by Shaderx** [b-morgan/Skillet#79]
5.04 Alpha 1
en-US

![Wow_LZ2nuhlPNf](https://user-images.githubusercontent.com/10783174/212408220-48b4df03-93b8-4d68-bc55-9e8b63aab1ee.png)
![Wow_gBtG76LppL](https://user-images.githubusercontent.com/10783174/212408284-d3d0ea09-a5fa-4fe7-b981-d0c637085ba3.png)

Cast bar succeeded but item not created.

Any idea why?

On further testing, creating the amulet by itself when i have all the mats will still queue a shimmering clasp.
Creating a shimmering clasp in skillet by itself works.
Queueing the amulet and then deleting the excessed queue shimmering clasp then starting the queue works.
Starting the queue with the additional shimmering clasp gives the above error.

**Comment by b-morgan** [comment]
You have encountered my biggest frustration... the event UNIT_SPELLCAST_FAILED_QUIET tells me nothing about "why" it failed. I'm guessing that Blizzard didn't like the contents of "{table}". Please add a couple more commands, "/skillet tabledump on" and "/skillet debuglevel 4". These two commands will generate a lot more "spam" in chat. You can check the state of Skillet's debugging with "/skillet debugstatus". 

Skillet also logs the chat output to a size-limited table in memory (when full, the oldest output is deleted as newer output is added). This table is written out to the character specific saved variables file, Skillet.lua, when you logoff or "/reload". "/skillet debugshow off" will stop the chat "spam" but you need "/skillet debuglogging off" to stop the output to the in memory table.

You can post a zip of the character specific saved variable file here (GitHub won't take .lua files).

Once the contents of {table} is revealed, I can determine what Skillet did wrong in creating it and hopefully fix it. I will need your help because my Jeweler is only level 47. In the mean time, I'll do some testing with my Engineer and see if a similar failure occurs.

**Comment by b-morgan** [comment]
Please also post a zip of your global saved variables file. Since it is also named Skillet.lua, you may need to rename the character specific file if you want to put them both in the same zip file.

I may also have to add more debug statements to the code and get it to you for more testing.

**Comment by Shaderx** [comment]
[Skillet logs.zip](https://github.com/b-morgan/Skillet/files/10417136/Skillet.logs.zip)
Here you are!

**Comment by b-morgan** [comment]
I think I found the problem. [Skillet-5.04-alpha2](https://www.curseforge.com/wow/addons/skillet/files/4332358) should fix it. 

I can't test it so you'll have to let me know.

**Comment by b-morgan** [comment]
[Skillet-5.04-alpha3](https://www.curseforge.com/wow/addons/skillet/files/4333699) is also available (other unrelated to this issue fixes).

**Comment by b-morgan** [comment]
Bad news... Judging from how poorly 5.04-alpha2 performed with engineering, I think it will fail miserably with jewelcrafting.

Good news... [Skillet-5.04-alpha6](https://www.curseforge.com/wow/addons/skillet/files/4339408) is performing much better with engineering.

Give this one (or anything newer when you read this) a try and let me know how it works for you.

**Comment by b-morgan** [comment]
[Skillet-5.04](https://www.curseforge.com/wow/addons/skillet/files/4351754) has been released. If there is still an issue, please open a new issue.
