### ISSUE TITLE
Skillet Doesn't open when there is no old world training via macro.

### ISSUE THREAD

**Issue by Shaderx** [b-morgan/Skillet#81]
5.04
en-gb

Skillet doesn't open skillet window when there is no old world training if /cast alchemy is used in a macro to open said tradeskill window.

For example df alchemy on a fresh 60, clicking on the alchemy in the book opens it, but using /cast alchemy on a macro does not open it.

Training any old school alchemy allows me to open it again.

Did not occur prior to 22nd 06 2023 patch.

**Comment by Shaderx** [comment]
Can't reproduce on 2nd character. Will test more.

**Comment by b-morgan** [comment]
If you get another failure, please type `/skillet debugshow`, `/skillet tabledump`, `/skillet debuglevel 4`, '/skillet traceshow`, and reproduce to capture Skillet debug output. This output will appear in chat and will be stored in the character specific saved variables file, Skillet.lua. Please zip this file and upload it here. Type `/skillet debugoff` to turn off debugging.

**Comment by b-morgan** [comment]
Since I just happen to have a fresh 60, I tried this and could not reproduce.

Do you have a macro with multiple professions which uses Shift, Ctrl, and Alt to determine which profession to open? If so, type `/skillet nomodkeys` and see if that fixes the issue. 

Since Skillet doesn't completely replace the Blizzard UI, there is a button on the Skillet frame to open the Blizzard UI. If this button doesn't work, you may need to use `/skillet standby` (or `/skillet standby on` and `/skillet standby off` so that your macro will open the Blizzard UI instead when needed.

**Comment by b-morgan** [comment]
If this is still a problem, please reopen this issue or open a new one.
